# docker-compose.yml
version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./app/:/app/src/
    environment:
      NODE_ENV: development

  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo  # Utilisez le nouveau Dockerfile pour le service mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/sauvegarde:/data/sauvegarde"